### ISSUE TITLE
Inconsistent colours in switch and select statements

### ISSUE THREAD

**Issue by Nefendi** [LunarVim/onedarker.nvim#13]
Hi, Chris!

I love the colour scheme (fantastic job on that!) but one thing that's been bothering me for some time's the highlighting in switch statements. It seems that the `default` keyword's not treated the same as its siblings (at least in Go and C++ but I'm pretty sure that the language doesn't matter).

![image](https://user-images.githubusercontent.com/28621696/179390323-677cba81-34cf-4e10-9eb2-a8ad5f479945.png)

I'm attaching the output from `TSHighlightCapturesUnderCursor` for reference:

![image](https://user-images.githubusercontent.com/28621696/179390671-950c70a8-621f-4790-af4d-8baa6520da93.png)

![image](https://user-images.githubusercontent.com/28621696/179390686-60ca3a42-99d1-42b9-bba8-f69a199f7652.png)

In Go, something similar happens for the `select` statement which really's a conditional statement, too:

![image](https://user-images.githubusercontent.com/28621696/179390736-45c19d9a-d29b-4365-a488-7ab431447b91.png)

![image](https://user-images.githubusercontent.com/28621696/179390781-42fd6fd1-033e-47f6-bb32-ba3f4e5336fe.png)

![image](https://user-images.githubusercontent.com/28621696/179390794-9aad935f-2b65-4497-bc3b-b4000643ff5e.png)

![image](https://user-images.githubusercontent.com/28621696/179390804-29ba39c7-91ed-4a04-af27-7e610d963d56.png)

I don't know if anything can be done about it on the side of a colour scheme (maybe it is a Treesitter quirk) but please do let me know if I can help in any way!

**Comment by acass91** [comment]
Oddly enough, I get different results where the 'case' and 'default' are not highlighted.

![image](https://user-images.githubusercontent.com/6621993/195961613-081d3420-8ed2-4d81-ab9d-d9d79a6c9a2b.png)
